apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: dev
servers: 1
image: rancher/k3s:v1.28.1-k3s1
ports:
  - port: 80:80
  - port: 443:443
options:
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - server:*
