name: "🚀 Feature Request"
description: Suggest an idea for this project
title: "[Feature] "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature - all feedback is appreciated!
        Please fill in as much of the following form as you're able.
  - type: input
    attributes:
      label: Name and Version
      description: Name and version of the affected chart
      placeholder: knative-eventing 0.1.0
    validations:
      required: true
  - type: textarea
    attributes:
      label: What is the problem this feature will solve?
    validations:
      required: true
  - type: textarea
    attributes:
      label: What is the feature you are proposing to solve the problem?
      description: Describe the requests. If you already have something in mind... PRs are welcome!
    validations:
      required: true
  - type: textarea
    attributes:
      label: What alternatives have you considered?
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: |
        By submitting this issue, you agree to follow our
        [Code of Conduct](https://github.com/Ahhhh-man/charts/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
