# Copyright 2024 Ahhhh-man. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

## Global Docker image parameters
## Please, note that this will override the image parameters, including dependencies, configured to use the global value
## Current available global Docker image parameters: imageRegistry and imagePullSecrets
## @section Global parameters
## @param global.imageRegistry Global Docker image registry
## @param global.imagePullSecrets Global Docker registry secret names as an array
## @param global.defaultStorageClass Global default StorageClass for Persistent Volume(s)
##
global:
  imageRegistry: ""
  imagePullSecrets: []
  defaultStorageClass: ""

## @section Common parameters
##

## @param commonLabels Labels to add to all deployed objects (sub-charts are not considered)
##
commonLabels:
  global-label: ""
## @param commonAnnotations Annotations to add to all deployed objects
##
commonAnnotations: {}

## @section net-kourier configmaps
##
config:
  kourier:

## @section net-kourier components
##
controller:
  image:
    registry: gcr.io/knative-releases
    repository: knative.dev/net-kourier/cmd/kourier
    tag: ""
    digest: sha256:b53b3b680ef1f3cca83740d9e667f60b3581574b95a365dc7a1b9ce3fdd96aa6
    pullPolicy: IfNotPresent
    pullSecrets: []

gateway:
  image:
    registry: docker.io
    repository: envoyproxy/envoy
    tag: v1.31-latest
    digest: ""
    pullPolicy: IfNotPresent
    pullSecrets: []
