apiVersion: networking.internal.knative.dev/v1alpha1
kind: Certificate
metadata:
  name: routing-serving-certs
  namespace: {{ .Release.Namespace }}
  labels:
    networking.knative.dev/certificate-type: system-internal
    {{ include "knative-serving.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install
    networking.knative.dev/certificate.class: cert-manager.certificate.networking.knative.dev
    {{ include "knative-serving.annotations" . | nindent 4 }}
spec:
  dnsNames:
    - kn-routing
    - data-plane.knative.dev # for reverse-compatibility with net-* implementations that do not work with multi-SANs
  secretName: routing-serving-certs
