releases:
  - name: knative-serving
    namespace: knative-serving
    chart: oci://ghcr.io/ahhhh-man/charts/knative-serving
    version: "*"
    values:
      - config:
          domain:
            example.localhost: ""
          network:
            ingress-class: kourier.ingress.networking.knative.dev
          autoscaler:
            min-scale: "1"
            max-scale: "5"
            max-scale-limit: "100"
            initial-scale: "0"
            allow-zero-initial-scale: "true"
            scale-down-delay: "1m"
            stable-window: "30s"

  - name: kourier
    namespace: kourier-system
    chart: oci://ghcr.io/ahhhh-man/charts/kourier
    version: "*"

  - name: net-kourier
    namespace: knative-serving
    chart: oci://ghcr.io/ahhhh-man/charts/net-kourier
    version: "*"
