repositories:
  - name: incubator
    url: https://charts.helm.sh/incubator

releases:
  - name: knative-serving
    namespace: knative-serving
    chart: oci://ghcr.io/ahhhh-man/charts/knative-serving
    version: "*"
    values:
      - config:
          domain:
            example.localhost: ""
          network:
            ingress-class: kourier.ingress.networking.knative.dev

  - name: kourier
    namespace: kourier-system
    chart: oci://ghcr.io/ahhhh-man/charts/kourier
    version: "*"

  - name: net-kourier
    namespace: knative-serving
    chart: oci://ghcr.io/ahhhh-man/charts/net-kourier
    version: "*"

  - name: knative-eventing
    namespace: knative-eventing
    chart: oci://ghcr.io/ahhhh-man/charts/knative-eventing
    version: "*"
    values:
      - mtping:
          enabled: false
        jobsink:
          enabled: false
