repositories:
- name: jetstack
  url: https://charts.jetstack.io
- name: incubator
  url: https://charts.helm.sh/incubator

releases:
- name: cert-manager
  namespace: cert-manager
  chart: jetstack/cert-manager
  version: 1.18.2
  values:
    - crds:
        enabled: true

- name: selfsigned-issuer
  namespace: cert-manager
  chart: incubator/raw
  needs:
    - cert-manager
  values:
    - resources:
        - apiVersion: cert-manager.io/v1
          kind: ClusterIssuer
          metadata:
            name: cluster-selfsigned-issuer
          spec:
            selfSigned: {}
        - apiVersion: cert-manager.io/v1
          kind: ClusterIssuer
          metadata:
            name: knative-selfsigned-issuer
          spec:
            ca:
              secretName: knative-selfsigned-ca
        - apiVersion: cert-manager.io/v1
          kind: Certificate
          metadata:
            name: knative-selfsigned-ca
            namespace: cert-manager
          spec:
            secretName: knative-selfsigned-ca
            commonName: knative.dev
            usages:
              - server auth
            isCA: true
            issuerRef:
              kind: ClusterIssuer
              name: cluster-selfsigned-issuer

- name: knative-serving
  namespace: knative-serving
  chart: oci://ghcr.io/ahhhh-man/charts/knative-serving
  version: "*"
  values:
    - config:
        domain:
          example.localhost: ""
        network:
          ingress-class: kourier.ingress.networking.knative.dev
          domain-template: "{{ `{{ .Name }}.{{ .Domain }}` }}"
          autocreate-cluster-domain-claims: "true"
          external-domain-tls: Enabled
          http-protocol: Redirected
          default-external-scheme: "https"
          namespace-wildcard-cert-selector: |-
            matchExpressions:
            - key: "networking.knative.dev/disableWildcardCert"
              operator: "NotIn"
              values: ["true"]
        certmanager:
          issuerRef: |
            kind: ClusterIssuer
            name: knative-selfsigned-issuer

- name: kourier
  namespace: kourier-system
  chart: oci://ghcr.io/ahhhh-man/charts/kourier
  version: "*"

- name: net-kourier
  namespace: knative-serving
  chart: oci://ghcr.io/ahhhh-man/charts/net-kourier
  version: "*"

- name: helloworld-go
  namespace: default
  chart: incubator/raw
  needs:
    - knative-serving/knative-serving
  values:
    - resources:
        - apiVersion: serving.knative.dev/v1
          kind: Service
          metadata:
            name: hello
          spec:
            template:
              spec:
                containers:
                  - image: ghcr.io/knative/helloworld-go:latest
                    ports:
                      - containerPort: 8080
                    env:
                      - name: TARGET
                        value: "World"
