# Copyright 2018 The Knative Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{- $autoscaler := .Values.autoscaler }}
{{- if $autoscaler.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoscaler
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: autoscaler
    {{ include "knative-serving.labels" . | nindent 4 }}
  annotations:
    {{ include "knative-serving.annotations" . | nindent 4 }}
spec:
  replicas: {{ $autoscaler.replicas }}
  selector:
    matchLabels:
      app: autoscaler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: autoscaler
        app.kubernetes.io/component: autoscaler
        {{ include "knative-serving.labels" . | nindent 8 }}
    spec:
      {{- with $autoscaler.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 12 }}
      {{- end }}
      {{- with $autoscaler.affinity }}
      affinity:
        {{- toYaml . | nindent 12 }}
      {{- else }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: autoscaler
                topologyKey: kubernetes.io/hostname
              weight: 100
      {{- end }}
      {{- with $autoscaler.tolerations }}
      tolerations:
        {{- toYaml . | nindent 12 }}
      {{- end }}
      serviceAccountName: controller
      containers:
        - name: autoscaler
          image: {{ template "knative-serving.autoscaler.image" . }}
          imagePullPolicy: {{ $autoscaler.image.pullPolicy }}
          {{- if or $autoscaler.image.pullSecrets .Values.global.imagePullSecrets }}
          imagePullSecrets:
            {{- include "knative-serving.imagePullSecrets" (dict "root" . "imagePullSecrets" $autoscaler.image.pullSecrets) | nindent 8 }}
          {{- end }}
          {{- with $autoscaler.resources }}
          resources:
          {{- toYaml . | nindent 6 }}
          {{- else }}
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 1000m
              memory: 1000Mi
          {{- end }}
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SYSTEM_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CONFIG_LOGGING_NAME
              value: config-logging
            - name: CONFIG_OBSERVABILITY_NAME
              value: config-observability
            # TODO(https://github.com/knative/pkg/pull/953): Remove stackdriver specific config
            - name: METRICS_DOMAIN
              value: knative.dev/serving
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          ports:
            - name: metrics
              containerPort: {{ $autoscaler.containerPorts.metrics }}
            - name: profiling
              containerPort: {{ $autoscaler.containerPorts.profiling }}
            - name: websocket
              containerPort: {{ $autoscaler.containerPorts.websocket }}
          {{- with $autoscaler.livenessProbe }}
          livenessProbe:
          {{- toYaml . | nindent 6 }}
          {{- else }}
          livenessProbe:
            httpGet:
              port: websocket
            failureThreshold: 6
          {{- end }}
          {{- with $autoscaler.readinessProbe }}
          readinessProbe:
          {{- toYaml . | nindent 6 }}
          {{- else }} 
          readinessProbe:
            httpGet:
              port: websocket
          {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: autoscaler
  namespace: {{ .Release.Namespace }}
  labels:
    app: autoscaler
    app.kubernetes.io/component: autoscaler
    {{ include "knative-serving.labels" . | nindent 4 }}
  annotations:
    {{ include "knative-serving.annotations" . | nindent 4 }}
spec:  
  selector:
    app: autoscaler
  ports:
    - name: http-metrics
      port: 9090
      targetPort: {{ $autoscaler.containerPorts.metrics }}
    - name: http-profiling
      port: 8008
      targetPort: {{ $autoscaler.containerPorts.profiling }}
    - name: http
      port: 8080
      targetPort: {{ $autoscaler.containerPorts.websocket }}
{{- end }}
