# Copyright 2018 The Knative Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{- $webhook := .Values.webhook }}
{{- if $webhook.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: webhook
    {{ include "knative-serving.labels" . | nindent 4 }}
  annotations:
    {{ include "knative-serving.annotations" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: webhook
      role: webhook
  template:
    metadata:
      labels:
        app: webhook
        role: webhook
        app.kubernetes.io/component: webhook
        {{ include "knative-serving.labels" . | nindent 8 }}
    spec:      
      {{- with $webhook.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 12 }}
      {{- end }}
      {{- with $webhook.affinity }}
      affinity:
        {{- toYaml . | nindent 12 }}
      {{- else }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: webhook
                topologyKey: kubernetes.io/hostname
              weight: 100
      {{- end }}
      {{- with $webhook.tolerations }}
      tolerations:
        {{- toYaml . | nindent 12 }}
      {{- end }}
      serviceAccountName: controller
      containers:
        - name: webhook
          image: {{ template "knative-serving.webhook.image" . }}
          imagePullPolicy: {{ $webhook.image.pullPolicy }}
          {{- if or $webhook.image.pullSecrets .Values.global.imagePullSecrets }}
          imagePullSecrets:
            {{- include "knative-serving.imagePullSecrets" (dict "root" . "imagePullSecrets" $webhook.image.pullSecrets) | nindent 8 }}
          {{- end }}
          {{- with $webhook.resources }}
          resources:
          {{- toYaml . | nindent 6 }}
          {{- else }}
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 500m
              memory: 500Mi
          {{- end }}
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: SYSTEM_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CONFIG_LOGGING_NAME
              value: config-logging
            - name: CONFIG_OBSERVABILITY_NAME
              value: config-observability
            - name: WEBHOOK_NAME
              value: webhook
            - name: WEBHOOK_PORT
              value: "8443"
            # TODO(https://github.com/knative/pkg/pull/953): Remove stackdriver specific config
            - name: METRICS_DOMAIN
              value: knative.dev/internal/serving
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          ports:
            - name: metrics
              containerPort: {{ $webhook.containerPorts.metrics }}
            - name: profiling
              containerPort: {{ $webhook.containerPorts.profiling }}
            - name: https-webhook
              containerPort: {{ $webhook.containerPorts.https }}
          {{- with $webhook.livenessProbe }}
          livenessProbe:
          {{- toYaml . | nindent 6 }}
          {{- else }}
          livenessProbe:
            periodSeconds: 10
            httpGet:
              scheme: HTTPS
              port: https-webhook
            failureThreshold: 6
            initialDelaySeconds: 20
          {{- end }}
          {{- with $webhook.readinessProbe }}
          readinessProbe:
          {{- toYaml . | nindent 6 }}
          {{- else }} 
          readinessProbe:
            periodSeconds: 1
            httpGet:
              scheme: HTTPS
              port: https-webhook
          {{- end }}
      # Our webhook should gracefully terminate by lame ducking first, set this to a sufficiently
      # high value that we respect whatever value it has configured for the lame duck grace period.
      terminationGracePeriodSeconds: {{ $webhook.terminationGracePeriodSeconds }}
---
apiVersion: v1
kind: Service
metadata:
  name: webhook
  namespace: {{ .Release.Namespace }}
  labels:
    app: webhook
    role: webhook
    app.kubernetes.io/component: webhook
    {{ include "knative-serving.labels" . | nindent 4 }}
  annotations:
    {{ include "knative-serving.annotations" . | nindent 4 }}
spec:  
  selector:
    app: webhook
    role: webhook
  ports:
    - name: http-metrics
      port: 9090
      targetPort: {{ $webhook.containerPorts.metrics }}
    - name: http-profiling
      port: 8008
      targetPort: {{ $webhook.containerPorts.profiling }}
    - name: https-webhook
      port: 443
      targetPort: {{ $webhook.containerPorts.https }}
{{- end }}
