# Copyright 2020 The Knative Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{- $jobsink := .Values.jobsink }}
{{- if and $jobsink.enabled $jobsink.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $jobsink.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "knative-eventing.labels" . | nindent 4 }}
  annotations:
    {{- with $jobsink.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: knative-eventing-job-sink
  labels:
    {{- include "knative-eventing.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ $jobsink.serviceAccount.name }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: knative-eventing-job-sink
  apiGroup: rbac.authorization.k8s.io
{{- end }}
